Update patch set 1
Patch Set 1:

> Why was this needed?

I was getting this exception

Traceback (most recent call last):
  File "/usr/bin/external-naginator", line 9, in <module>
    load_entry_point('ExternalNaginator==0.0.1', 'console_scripts', 'external-naginator')()
  File "/usr/lib/python2.7/dist-packages/external_naginator/__init__.py", line 664, in main
    cfg.generate_all()
  File "/usr/lib/python2.7/dist-packages/external_naginator/__init__.py", line 541, in generate_all
    nagios_hosts=self.nagios_hosts)
  File "/usr/lib/python2.7/dist-packages/external_naginator/__init__.py", line 103, in __init__
    self.nodefacts = self.get_nodefacts()
AttributeError: 'NagiosServiceGroup' object has no attribute 'get_nodefacts'

when nodefacts was returning as an empty dict.
I think this was because the node actually had no facts, but I'm
still trying to figure out why that is.

Patch-set: 1
Reviewer: Gerrit User 1000105 <1000105@f182a8af-62ca-4ceb-ab81-14f8fec9c6c5>
Label: Verified=0